In [44]:
from pandas import DataFrame,Series

In [8]:
# 从 Series 构造
d1 = {'conlumn1':Series([1,2,3],index = ['row11','row12','row13']),
     'conlumn2':Series([4,5,6],index = ['row21','row22','row23']),
     'conlumn3':Series([7,8,9],index = ['row31','row32','row33'])}
dataFrame1 = DataFrame(d1)
print(dataFrame1)

print('--------------------------------------------')

d2 = {'conlumn1':Series([1,2,3],index = ['row1','row2','row3']),
     'conlumn2':Series([4,5,6],index = ['row1','row2','row3']),
     'conlumn3':Series([7,8,9],index = ['row1','row2','row3'])}
dataFrame2 = DataFrame(d2)
print(dataFrame2)

       conlumn1  conlumn2  conlumn3
row11       1.0       NaN       NaN
row12       2.0       NaN       NaN
row13       3.0       NaN       NaN
row21       NaN       4.0       NaN
row22       NaN       5.0       NaN
row23       NaN       6.0       NaN
row31       NaN       NaN       7.0
row32       NaN       NaN       8.0
row33       NaN       NaN       9.0
--------------------------------------------
      conlumn1  conlumn2  conlumn3
row1         1         4         7
row2         2         5         8
row3         3         6         9


In [28]:
#  从 numpy数组 构建
import numpy as np
d3 = np.arange(12).reshape([3,4])
print(d3)
print('-----------------------')
dataFrame3 = DataFrame(d3,columns = ['col1','col2','col3','col4'],index =['row1','row2','row3'])
print(dataFrame3)
print()
print(dataFrame3['col1'])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------
      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

row1    0
row2    4
row3    8
Name: col1, dtype: int32


In [23]:
# 从 list的dict 构建
d4 = [{'a':1,'b':2},{'a':3,'b':4}]
dataFrame4 = DataFrame(d4,index = ['row1','row2'])
print(dataFrame4)

      a  b
row1  1  2
row2  3  4


In [15]:
# 构建的比较
import numpy as np
d5 = DataFrame({'col1':Series([1,2,3],index = ('a','b','c')),
              'col2':Series([4,5,6],index = ('a','b','c')),
              'col3':Series([7,8,9],index = ('a','b','c'))})
print(d5)
print('-----------------------------')

d7 = DataFrame({'col1':Series([1,2,3]),
              'col2':Series([4,5,6]),
              'col3':Series([7,8,9])},index = ('a','b','c'))
print(d7)#Series 中没有index为abc 它的index应该为默认的1 2 3 所以为NaN 
print('-----------------------------')

d6 = DataFrame({'col1':[1,2,3],
              'col2':[4,5,6],
              'col3':[7,8,9]},index = ('a','b','c'))
print(d6)
print('-----------------------------')

d8 = DataFrame(np.arange(9).reshape([3,3]),index = ('a','b','c'),columns = ('col1','col2','col3'))
print(d8)

   col1  col2  col3
a     1     4     7
b     2     5     8
c     3     6     9
-----------------------------
   col1  col2  col3
a   NaN   NaN   NaN
b   NaN   NaN   NaN
c   NaN   NaN   NaN
-----------------------------
   col1  col2  col3
a     1     4     7
b     2     5     8
c     3     6     9
-----------------------------
   col1  col2  col3
a     0     1     2
b     3     4     5
c     6     7     8


In [70]:
d9 = DataFrame(np.random.randn(3,3),index = ('a','b','c'),columns = ('col1','col2','col3'))

print('d9:')
print(d9)
print()

# print('describe:')
# print(d9.describe())

# 按照某一行某一列排序
print('sort_values:')
print(d9.sort_values(by = 'col1'))
print()
print('sort_index:')
print(d9.sort_index(axis=0,ascending=True))

#行切片
print()
print(d9[:1])

print()
print(d9.at['a','col1'])

print()
print(d9.loc['a','col1'])

print()
print(d9.loc[:,['col1','col2']])

print()
print(d9.loc[['a','b'],['col1','col2']])

d9:
       col1      col2      col3
a  1.107258  0.147878  0.070880
b -0.177568 -0.065564  0.285068
c  2.235347  0.308207  1.077258

sort_values:
       col1      col2      col3
b -0.177568 -0.065564  0.285068
a  1.107258  0.147878  0.070880
c  2.235347  0.308207  1.077258

sort_index:
       col1      col2      col3
a  1.107258  0.147878  0.070880
b -0.177568 -0.065564  0.285068
c  2.235347  0.308207  1.077258

       col1      col2     col3
a  1.107258  0.147878  0.07088

1.10725806146

1.10725806146

       col1      col2
a  1.107258  0.147878
b -0.177568 -0.065564
c  2.235347  0.308207

       col1      col2
a  1.107258  0.147878
b -0.177568 -0.065564


In [74]:
d10 = DataFrame({'col1':[1,2,3],
              'col2':[4,5,6],
              'col3':[7,8,9]},index = ('row1','row2','row3'))
print(d10)

print()
print(d10.iloc[1])
print()
print(d10.loc[:,'col1'])
print()
print(d10.iloc[1:,1:])
print(d10.iloc[[0,1],[0,1]])

print()
print(d10.at['row1','col1'])
print(d10.iat[0,0])

      col1  col2  col3
row1     1     4     7
row2     2     5     8
row3     3     6     9

col1    2
col2    5
col3    8
Name: row2, dtype: int64

row1    1
row2    2
row3    3
Name: col1, dtype: int64

      col2  col3
row2     5     8
row3     6     9
      col1  col2
row1     1     4
row2     2     5

1
1


In [2]:
import pandas as pd
from pandas import DataFrame,Series
d11 = DataFrame({'col1':[1,2,3],
              'col2':[4,5,6],
              'col3':[7,8,9]})

print(d11)


d11.loc[d11.shape[0]+1]={'col1':1,'col2':2,'col3':2}
print(d11)

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
4     1     2     2


In [5]:
val_acc_df = pd.DataFrame(columns=('step', 'value'))
print(val_acc_df)

val_acc_df.loc[val_acc_df.shape[0]+1]={'step':1,'value':2}
print(val_acc_df)

Empty DataFrame
Columns: [step, value]
Index: []
  step value
1    1     2
